tue-robotics/tue-env-targets

- ros/setup
So the node name is also printed.
> add ROSCONSOLE_FORMAT

- kaldi/install.bash
Previous variable name `BRANCH` breaks the installation.
> changed variable names

- ros-audio_capture/install.yaml
- ros-audio_common_msgs/install.yaml
Because https://github.com/tue-robotics/audio_common.git is matching upstream. So this repo can be deleted.
> Revert audio targets to debian

- ros/install.bash
Still need to run rosdep update after init. Adding this lined, broke the CI as image_recognition_msgs doesn't build because of rosdep not resolving.
> [HOTFIX] rosdep update

- hero1/setup
only use `hero-reboot` or `hero-shutdown`
No guarantees, Still gets into corrupted boot. But way less times.
Reboot is way more robust than shutdown.
> possible fix for hero start/reboot

- gazebo/install.bash
- gazebo/install.yaml
- hero1/install.yaml
- hsr-setup/install.bash
- hsr-setup/install.yaml
- ros-hsrb_description/install.yaml
- ros-tmc-desktop-full/install.yaml
- ros-tmc_msgs/install.yaml
- ros-tue_hsr/install.yaml
- ros/install.bash
> Refactor hsr-setup

- python-catkin-tools-document-pip/install.yaml
New release as mentioned in https://github.com/mikepurvis/catkin_tools_document/issues/12
> [python-catkin-tools-document] back to pip release

- ccache/setup
- cuda/setup
Direct exporting leads to pollution of the path variable when a terminal is resourced. This PR cleans up bash variables.
> Refactor export of variables

- tue-middleware/install.yaml
Not needed on HERO, used on AMIGO/SERGIO. but already included in amigo/sergio-start, so no need to be here too
> [tue-middleware] remove dep on tue_manipulation

- libfftw3/install.yaml
- ros-leg_tracker/install.yaml
libfftw3 matches rosdistro, https://github.com/ros/rosdistro/blob/9eb14c896d4b37e6467f39efbc00889b983c6b75/rosdep/base.yaml#L2025.
@TPCWester After this PR is merged, you can install the `leg_tracker` via tue-get, `tue-get install ros-leg_tracker`. This will override the symbolic link in the workspace. So the old cloned repo will not be used anymore in that case.
> Leg tracker targets

- .gitmodules
- .travis.yml
`tue-get` doesn't change the remote of the submodule.
Should only be merged if CI of https://github.com/tue-robotics/hero_bringup/pull/53 and https://github.com/tue-robotics/hero_bridge/pull/15 succeeds
> Move hsr-setup to private github repo

- ros-cb_base_navigation_msgs/install.yaml
In the meantime, github will redirect the old url to the new one
> [ros-cb_base_navigation_msgs] rename repo

- python-telegram-bot/install.yaml
Fixes datetime no arribute timezone
Needed because https://github.com/python-telegram-bot/python-telegram-bot/pull/1621 is not compatible with python2, which is added in 12.7.
> [python-telegram-bot] limit version because of python2 compatibility

- networking/install.yaml
Not installed by default on Ubuntu 18.04
> [networking] install net-tools for ifconfig

- ros-setup/install.bash
ROS forgot to update the expiration date of their GPG key: https://discourse.ros.org/t/ros-gpg-key-expiration-incident/20669
Generating a new docker image would fix CI, but not the local machines
Old image without check&update: https://github.com/tue-robotics/code_profiler/runs/2703509679?check_suite_focus=true
Old image with check&update: https://github.com/tue-robotics/code_profiler/runs/2703666019?check_suite_focus=true
> [ros-setup] Fix expired ROS GPG key

- ros/install.bash
This reduces the update time a little bit. Plus no need to pull the other distros.
> [ros] only run rosdep update on installed distro

- tue-documentation-github/install.yaml
Only used in fast_simulator, which is also closed to being deprecated. So no need for documentation generation. Also because there are no docstrings
> [tue-documentation-github] remove ros-virtual_cam

- python3-catkin-tools/install.yaml
Because of breaking change (https://github.com/tue-robotics/tue-env-targets/pull/282)
> [python3-catkin-tools] switch to pip target to limit version

- python3-catkin-tools/check_installed_version.py
- python3-catkin-tools/install.bash
Only when not meeting the minimal version, which would result in installing the system version on each run.
Fixes https://github.com/tue-robotics/tue-env-targets/issues/290
> [python3-catkin-tools] remove pip installed version

- colcon/install.yaml
- ros-setup/install.bash
- ros/install.bash
- ros/setup
- ros1/install.yaml
- ros2-setup/install.bash
- ros2/install.bash
- ros2/install.yaml
- ros2/setup
Merge before https://github.com/tue-robotics/tue-env/pull/620.
CI pipeline of 620 is dependent on this
> feat: Backport ros1 and ros2 targets from Avular

- amigo2/install.yaml
- hero-dev/install.yaml
- sergio2/install.yaml
- tue-dev/install.yaml
Missed files from https://github.com/tue-robotics/tue-env-targets/pull/338
> fix: tue-robocup-at-home has been replaced by ros-tue_robocup

- ros/install.bash
Old: https://github.com/tue-robotics/tue-env/actions/runs/4167154119/jobs/7212387099#step:4:1562
New: https://github.com/tue-robotics/tue-env/actions/runs/4167154119/jobs/7212658972#step:4:1579
Old:
```
#19 60.85 Starting >>> catkin_tools_prebuild                                             
#19 60.85 [build 0.1 s] [0/1 complete] [1/2 jobs] [0 queued] [catkin_tools_prebuild:c... 
[build 0.2 s] [0/1 complete] [1/2 jobs] [0 queued] [catkin_tools_prebuild:c... 
[build 0.3 s] [0/1 complete] [1/2 jobs] [0 queued] [catkin_tools_prebuild:c... 
[build 0.4 s] [0/1 complete] [1/2 jobs] [0 queued] [catkin_tools_prebuild:c... 
[build 0.5 s] [0/1 complete] [1/2 jobs] [0 queued] [catkin_tools_prebuild:c... 
[build 0.6 s] [0/1 complete] [1/2 jobs] [0 queued] [catkin_tools_prebuild:c... 
[build 0.7 s] …
```
> [ros] use `--no-status`  for tue-make in CI

- amigo-user/setup
- hero-demo-laptop/shortcuts/hero-rviz.desktop
- hero-demo-user/setup
- matthijs/setup
- qtcreator/README.md
- qtcreator/setup
- robot-demo-user/setup
- ros-swri_console/setup
- ros1/install.bash
- ros1/setup
- ros2/install.bash
- ros2/setup
- sergio-user/setup
- tue-documentation/README.md
- tue-documentation/setup
- tue_gazebo_plugins/setup
- vscode/install.bash
Tested with the master branch of tue-env, [tue-env#58854fd6efd03bd5700e0a6039c7a8dcb72dad79](https://github.com/tue-robotics/tue-env/tree/58854fd6efd03bd5700e0a6039c7a8dcb72dad79), in three different situations:
- https://github.com/tue-robotics/tue-robotics.github.io/actions/runs/8876108892
- https://github.com/tue-robotics/ed/actions/runs/8876682906
- https://github.com/tue-robotics/pykdl_ros/actions/runs/8879165488
> Updated TUE variable names

- python-sphinx-autoapi-pip/install.yaml
This reverts commit f37848f68f7e1eb28c361ec33b19f40d630472df.
Fixed by https://github.com/readthedocs/sphinx-autoapi/commit/1c0a669e85aa670ab768aed5f72082e313ef832e
> Revert "[python-sphinx-autoapi-pip][TEMP] limit version (#454)"
