kaldi/install.bash

clone techunited branch instead of master

Kaldi develop branch

---

atlas3/install.yaml
autoconf/install.yaml
automake/install.yaml
bzip2/install.yaml
gawk/install.yaml
grep/install.yaml
gzip/install.yaml
kaldi/install.bash
libtool/install.yaml
p7zip-full/install.yaml
patch/install.yaml
python-future/install.yaml
python-gi/install.yaml
subversion/install.yaml
swig/install.yaml
wget/install.yaml
zlib/install.yaml

Added new dependencies and updated install.bash

Kaldi dependencies

---

matthijs/setup

update setup of Matthijs target

---

cmdgen/install.bash
kaldi/install.bash

Merge after: https://github.com/tue-robotics/tue-env/pull/360

SSH support in targets

---

robot-user/setup

not really needed with ssh capabilities and very ugly code.

Remove github-cache-credentials

---

ros-ed_object_models/setup

Merge together with https://github.com/tue-robotics/ed_object_models/pull/43

ED_MODEL_PATH set in package

---

kaldi/install.bash

Kaldi docker builds are triggered manually. So there shouldn't be any update in Docker.

Do not rebuild Kaldi during tue-get update/install in Docker

---

git/gitignore_global

Qt likes to create more file when updating to another version.

ignore any CMakeLists.txt.user

---

ros/install.bash
ros/setup

unset CMAKE_PREFIX_PATH, before sourcing ws, so it keeps constant with multiple sources of setup.bash

Small fix in ros/setup

---

ros-teleop_twist_web/install.yaml

@timple to fix teleop_twist_web ci

[ros-teleop_twist_web] add target

---

robot/install.yaml

So on every robot pc it ask if user is correct before committing.

[robot] add git-hooks

---

ros-image_recognition_people_detector/install.yaml

Need to get rid of the version tag once tue-robotics/image_recognition#88 is merged

[1/2] Add people detector package

---

hero-dashboard/get-releases
hero-dashboard/install.bash
hero-dashboard/process-releases
hero-dev/install.yaml

hero-dashboard and hero-dashboard-localhost should be available after install
Please test.

Hero dashboard

---

hero-start/install.yaml

It is not used.
Merge AFTER https://github.com/tue-robotics/hero_bridge/pull/8

Remove dep on tue_manipulation in hero-start

---

python-packaging/install.yaml

This will be used in `image_recognition_keras` for version checking

[python-packaging] new target

---

ros/install.bash

Merge together with https://github.com/tue-robotics/tue-env/pull/415

[ros] Use tue-make for workspace creation

---

python-tensorflow-pip/install.bash

Merge after https://github.com/tue-robotics/image_recognition/pull/102

[python-tensorflow-pip] change version limits

---

python-nose/install.yaml

Merge before https://github.com/tue-robotics/action_server/pull/120

[python-nose] new target

---

hero-dashboard/install.bash
hero-dashboard/process-releases
hero-dashboard/setup

Merge after merging https://github.com/tue-robotics/hero-dashboard/pull/4 and creating a release.

[hero-dashboard] get rid of localhost release

---

gtest/install.yaml

Should fix CI of https://github.com/tue-robotics/geolib2/pull/34

[gtest] new target

---

ros/install.bash

[ros] supress apt-key warning

---

tinyxml2/install.yaml

Add tinyxml2

---

gazebo_models/install.bash

Merge after https://github.com/tue-robotics/tue-env/pull/453

[gazebo_models] tue-install-hg

---

.travis.yml
networking/install.bash

fixes tue-robotics/tue_robocup#1002

[networking] generate rsa4096 keys

---

ros-challenge_carry_my_luggage/install.yaml

Merge together with tue-robotics/tue_robocup#1020

Feature(tue-env): install for carry my luggage

---

gazebo/install.yaml

I think nothing depends on gazebo so this won't break anybody, but I'm trying to use it for https://github.com/Rayman/tue_rosdistro and it doesn't work the way it is now.

Fix gazebo target on xenial

---

networking/install.bash
pycharm/install.bash
qtcreator/install.bash
robot/install.bash
ros-image_recognition_keras/install.bash
vscode/install.bash

Review and merge after #183
Merge together with https://github.com/tue-robotics/tue-env/pull/530

Apply .ci_ignore

---

.travis.yml

Reduce CI time from 45 to 30 secs. Every ~vote~ second counts.

(travis) use python image

---

tue-documentation/setup

This reverts commit efa68405355c5ad82f7542e0caa50054f8a4a271.

Revert "[tue-documentation] remove -DCATKIN_ENABLE_TESTING=OFF"

---

python-tensorflow-pip/install.bash
python-tensorflow-pip/install.yaml

See: https://www.tensorflow.org/install/gpu#pip_package

tensorflow contains gpu support in main pkg

---

castxml/install.yaml

[castxml] new target

---

python-enum34/install.yaml

Used in https://github.com/tue-robotics/node_alive/pull/14

[python-enum34] new target

---

python/install.yaml
python3/install.yaml

Python targets

---

.github/dependabot.yml
chrome-dev/install.bash
chrome/install.bash
dropbox/install.bash
gazebo-setup/install.bash
jenkins/install.bash
ros-setup/install.bash

Merge after https://github.com/tue-robotics/tue-env/pull/555
Review and merge after https://github.com/tue-robotics/tue-env-targets/pull/208

Apply tue-install-apt-get-update

---

python-tensorboard-pip/install.yaml
ros/install.bash

Weird branch name is used in image_recognition

[python-tensorboard-pip] new target; rename rosdep update file

---

ros-tf2_kdl/install.yaml

Merge before https://github.com/tue-robotics/tue_robocup/pull/1100

[ros-tf2_kdl] new target

---

ros-setup/install.bash

[ros-setup] remove sudo from key check

---

ros-setup/install.bash

- This should be backwards compatible with existing ros sources file

feat: Robust handling of ROS GPG key

---

ed_data_storage/setup

[ed_data_storage] delete target

---

catkin-tools-setup/install.yaml
catkin/install.yaml
python3-catkin-tools/install.yaml
ros/install.yaml

New ppa as ros one will probably not get updated

catkin_tools update

---

ros-catkin/install.yaml

[ros-catkin] remove dep on ros-setup

---

gitsu/gitsu.txt

Add Shashank to gitsu

---

vscode/tasks.json

[vscode] Add forgotten tasks file

---

ros-armadillo_matrix/install.yaml

See https://github.com/tue-robotics/wire/pull/16

[ros-armadillo_matrix] pkg deleted

---

tue-documentation-github/install.yaml

[tue-documentation-github] remove dep on people_msgs

---

ros-problib_msgs/install.yaml
tue-documentation-github/install.yaml

Merge together with https://github.com/tue-robotics/wire/pull/28

[ros-problib_msgs] new target

---

.github/dependabot.yml

This reverts commit e09091ccfeaa4dc92a4def6dd2680e77708dae6c.

Add dependabot for submodules

---

ros-ed/setup

Merge with: https://github.com/tue-robotics/ed/pull/130

[ros-ed] no need for custom plugin_path anymore

---

ros-image_recognition_pytorch/install.bash
ros-image_recognition_pytorch/install.yaml

Installer for https://github.com/tue-robotics/image_recognition/pull/146

Add installer for image_recognition_pytorch

---

python3-catkin-tools/install.yaml

See https://github.com/catkin/catkin_tools/pull/712 and https://github.com/mikepurvis/catkin_tools_document/pull/25

[python3-catkin-tools] limit catkin version because of breaking change

---

python3-catkin-tools/install.yaml

Will move back to system, when that is available too

[python3-catkin-tools] fixed version has been released on pip

---

python-serial/install.yaml
ros-xsens_driver/install.yaml

Used by `sergio_torso_calibration`

Fix xsens driver

---

facets/install.yaml
gitsu/install.bash
gitsu/install.yaml

Merge after https://github.com/tue-robotics/tue-env/pull/616

Support Gems

---

clion/clion_clion.desktop
clion/install.bash
clion/install.yaml

New target for you @PetervDooren

[clion] new target

---

openface/torch.bash

[openface] add missing slash

---

at-home-refbox-dev/install.bash
cmdgen/install.bash
dashboard-dev/install.bash
gazebo_models/install.bash
hero-dashboard-dev/install.bash
hero-display-dev/install.bash
kaldi/install.bash
matthijs/install.bash
openface/install.bash
openface/torch.bash
vim/install.bash

Merge together with https://github.com/tue-robotics/tue-env/pull/620

Apply changes to tue-install-git

---

hero2/install.yaml
tue-robocup-at-home/install.yaml

Merge after https://github.com/tue-robotics/tue_robocup/pull/1262

[tue-robocup-at-home] remove target

---

tue-documentation-github/install.yaml

This needs to wait for the packages to be merged

[tue-documentation-github] add new challenges

---

python-xhtml2pdf-pip/install.yaml

https://github.com/pygobject/pycairo/issues/319

[python-xhtml2pdf-pip][TEMP] add libcairo2-dev

---

ros-image_recognition_footwear/install.yaml

[ros-image_recognition_footwear] new target

---

python3-telegram-bot/install.yaml
ros-telegram_ros/install.yaml

Back-up for when https://github.com/tue-robotics/telegram_ros/pull/33 not working

Telegram < 20

---

python3-sklearn/install.yaml

Needed for numpy compatibility

[python3-sklearn] convert to pip, >=1.0

---

python-sphinx-autoapi-pip/install.yaml

TEMP fix for https://github.com/tue-robotics/tue-robotics.github.io/issues/43

[python-sphinx-autoapi-pip][TEMP] limit version
